### PR TITLE
Bump machine-api-operator to 25e61c2

### PR DESCRIPTION
**Pull request by damdo**
It bumps machine-api-operator to the latest revision.

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by damdo** [comment]
The `e2e-gcp-operator-test` actually passed here: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-provider-gcp/10/pull-ci-openshift-machine-api-provider-gcp-main-e2e-gcp-operator/1524161409393364992 it in fact was the cluster teardown that failed which later failed the entire job.

After consulting with @JoelSpeed about this, we think it's safe to override.
/override e2e-gcp-operator

**Pull request merged**
