### PR TITLE
MGMT-12838: Add Shielded VMs implementation

### PR DESCRIPTION
**Pull request by eranco74**
Add support to Shielded VMs on GCP
Feature link: https://issues.redhat.com/browse/OCPBU-158

### CODE REVIEW

**Comment by JoelSpeed** [comment]
@sunzhaohua2 Can we pre-merge test this and make sure this works as expected?

**Comment by eranco74** [comment]
@sunzhaohua2 any update?

**Comment by sunzhaohua2** [comment]
@eranco74 @JoelSpeed really sorry, I missed this pr.
@miyadav can you help on this?

**Comment by miyadav** [comment]
@eranco74 , @JoelSpeed added comments on - OCPCLOUD-1828 , please review.

**Pull request merged**
