### PR TITLE
OCPBUGS-30520: Bump protobuf to v1.34.0

### PR DESCRIPTION
**Pull request by racheljpg**
Hello! This is a PR to bump protobuf to v1.34.0 for a CVE fix. Thanks!

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Looks like another `go mod tidy && go mod vendor` is needed here

**Comment by racheljpg** [comment]
Thanks @JoelSpeed, was just at it when you commented :) seems good now

**Review by JoelSpeed — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
