### PR TITLE
update windows script handling

### PR DESCRIPTION
**Pull request by elmiko**
this change removes the code that would look specifically for the windows powershell secret. instead it relies on the normal user data from the `userDataSecret` in conjuction with the windows o/s label to inject the windows script in the proper metadata key.

this change does preserve the behavior for the user to specify values in
the metadata which will override the values from the secret.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Changes LGTM but QE didn't get it to work, let's make sure they're happy before we merge (may need to make this a bug)

**Comment by elmiko** [comment]
+1, i've left some comments with QE. need to work out where the failure happened.

**Comment by elmiko** [comment]
it looks like this is working as expected, see [comment from qe on jira](https://issues.redhat.com/browse/OCPCLOUD-1568?focusedCommentId=20952374&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-20952374)

**Comment by elmiko** [comment]
/hold

found a bug that needs addressing

**Review by JoelSpeed — COMMENTED** [review]
/lgtm

**Pull request merged**
